artifacts_root: artifacts1


data_ingestion:
  root_dir: artifacts1/data_ingestion
  database_path: DATABASE1/CROP.DB
  table_name: crop_recommendation
  download_dir : artifacts1/data_ingestion

data_validation:
  root_dir: artifacts1/data_validation
  download_dir: artifacts1/data_ingestion/crop_recommandation.csv
  STATUS_FILE: artifacts1/data_validation/status.txt

data_transformation:
  root_dir: artifacts1/data_transformation
  data_path: artifacts1/data_ingestion/crop_recommandation.csv

model_trainer:
  root_dir: artifacts1/model_trainer
  train_data_path: artifacts1/data_transformation/train.csv
  test_data_path: artifacts1/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts1/model_evaluation
  test_data_path: artifacts1/data_transformation/test.csv
  model_path: artifacts1/model_trainer/model.joblib
  metric_file_name: artifacts1/model_evaluation/metrics.json